### PR TITLE
Completed Task-2

### PR DESCRIPTION
**Pull request by kushal7201**
Issue: #2 

Here is the Updated image of GrepIt logo:
brave_DoRHWdyy0I

Figma link to the Logo:
https://www.figma.com/file/gJjkVEQvu9tBzeMNG5VA9Z/GrepIt_Logo?type=design&node-id=0%3A1&mode=design&t=ioAYpgnOw4abHoQs-1

### CODE REVIEW

**Comment by shashank-lol** [comment]
Hi, try to think of a better way of representing the project. Be more innovative.

**Comment by kushal7201** [comment]
Ok

**Comment by kushal7201** [comment]
I have updated the logo. Please check @shashank-lol @bhupesh98

**Comment by shashank-lol** [comment]
Make the font size bigger

**Comment by kushal7201** [comment]
I have increased the size of the font. Please check @shashank-lol

**Pull request merged**
