### PR TITLE
Update glassMorf.json

### PR DESCRIPTION
**Pull request by sanju26honey**
Issue: #20 

#### Short description of what this resolves:
Added GlassMorphism output and code

#### Changes proposed in this pull request and/or Screenshots of changes:
GlassMorphismOutput

### CODE REVIEW

**Comment by shashankpatil28** [comment]
@sanju26honey Unfortunately, we've decided not to implement the glass morph feature in our application due to insufficient response and challenges in meeting expectations on the open-for-all issue. Therefore, we are closing that particular issue.

**Comment by sanju26honey** [comment]
Hey!
But I see you have merged and closed 3 other pull requests, and also given the points, then why not for this?

**Comment by shashankpatil28** [comment]
They were comparatively better than your PR. Unfortunately.

**Comment by sanju26honey** [comment]
Okay, Thanks!

**Pull request closed without merging**
